### ISSUE TITLE
Todos os membros da equipe acessem a plataforma constantemente  

### ISSUE THREAD

**Issue by DanielleAraujo** [DanielleAraujo/PROJETO-OFICIAL#19]
Gostaria que todos abrissem o GitHub para verificar suas atividades.

**Comment by DanielleAraujo** [comment]
- CLP 

- Válvula Hidráulica

**Comment by Rayara** [comment]
Ok Dani! Verificarei constantemente o GitHub

**Comment by hyperiondeimos** [comment]
Idem ao item do scrum. Porém esse item eu fecharei normalmente.
