### ISSUE TITLE
Definição do produto que vamos trabalhar

### ISSUE THREAD

**Issue by DanielleAraujo** [DanielleAraujo/PROJETO-OFICIAL#23]
Temos que definir o produto que temos que trabalhar para poder definir os possíveis defeitos

**Comment by DanielleAraujo** [comment]
Produto: Embalagem de celular (verificação de todos os componentes da caixa)

A ideia é que o operador identifique quais as caixas de celulares estão com ausência de componentes. Quais estiverem, voltam pra linha. As completas são liberadas.

**Comment by hyperiondeimos** [comment]
Definido o RFID. Agora deve ser levantado os custos do projeto. Fazer isso na sprint #2 por favor. @DanielleAraujo
