### ISSUE TITLE
Pesquisar quais os possíveis congressos ou simpósios para publicação 

### ISSUE THREAD

**Issue by DanielleAraujo** [DanielleAraujo/PROJETO-OFICIAL#6]
Seria bom ver congressos, simpósios nacionais que sejam relevantes para nossa área. E verifiquem os modelos de artigos para submissão.

**Comment by DanielleAraujo** [comment]
[CONGRESSO BRASILEIRO DE AUTOMÁTICA](http://www.ufpb.br/cba2018/)

[3º Congresso Nacional Online de Engenharia Mecânica e Automação](https://conaenge.com.br/ )

**Comment by Rayara** [comment]
[Conferência Internacional de Automação Industrial, Robótica e Engenharia de Controle]
(http://www.iarce.org/)

[DINAME – XVII Simpósio Internacional sobre Problemas Dinâmicos de Mecânica]
(https://eventos.abcm.org.br/diname2017/)

**Comment by Rayara** [comment]
[Conferência Internacional de Automação Industrial, Robótica e Engenharia de Controle](http://www.iarce.org/)

[DINAME – XVII Simpósio Internacional sobre Problemas Dinâmicos de Mecânica](https://eventos.abcm.org.br/diname2017/)

**Comment by hyperiondeimos** [comment]
Faltam 4 eventos de 8. Atualizar por favor.
